name: rag_from_wiki
description: Workflow implementation of RAG, which loader ducoment and retrieval from vector database.
jobs:
  
  - name: 分析如何从wiki中找哪些Docuement 
    type: prompt
    description: think how to get document from wiki
    llm_provider: openai
    llm_model: anthropic/claude-3.5-haiku
    temperature: 0.5
    system_prompt: |
      Try to regenerate based on the question, for corpus retrieval questions optimized for vector library and keywords, the question you provide will be used to retrieve higher quality documents from the corpus. 
      
      Output the whole process within the appropriate XML tags:
      <question_rephrased>
        [Insert your rephrased question here]
      </question_rephrased>

    template: |
      question:
      {{.question}}

    params:
      - question
    output:
      - question_rephrased

  - name: retrieval_doc
    type: search
    description: Retrieve document from vector database
    corpus: 语料库-测试-1
    query_field: question_rephrased
    output_field: search_result
    search_options:
      query_size: 3
      block_size: 10000
  
  - name: rag
    type: prompt
    description: RAG
    llm_provider: openai
    llm_model: anthropic/claude-3.5-haiku
    temperature: 0.5
    system_prompt: |
      You are a helpful assistant that can answer questions about a specific document.
      
      First, you should rephrase the question to make it more detailed and easier to answer.
      Then, Let's think step by step, We can refer to the content in the document, use the content to refine the current step.
      Finally, give your answer.


      Output
      output the whole process within the appropriate XML tags: 
      <step1_rephrased_question>

        [Insert the complete rephrased question here]

      </step1_rephrased_question>

      <step2_thought>
        [Insert your thinking process here]
      </step2_thought>

      <step3_output>
        [Insert your answer here]
      </step3_output>

    template: |
      document:
      {{.search_result}}
      question:
      {{.question_rephrased}}

    params:
      - search_result
      - question_rephrased
    output:
      - step1_rephrased_question
      - step2_thought
      - step3_output

