// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: corpus.sql

package db

import (
	"context"
	"database/sql"
)

const createCorpus = `-- name: CreateCorpus :one
INSERT INTO corpus (name, description, collection_name, rerank_fusion_method, use_bm25_index, use_context_embed, embedding_provider, embedding_model, embedding_options, vector_store, vector_dimension, vector_metric_type, context_embed_prompt)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, collection_name, rerank_fusion_method, vector_store, use_bm25_index, use_context_embed, created_at, last_updated_at, embedding_provider, embedding_model, embedding_options, vector_dimension, vector_metric_type, context_embed_prompt
`

type CreateCorpusParams struct {
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	CollectionName     sql.NullString `json:"collection_name"`
	RerankFusionMethod sql.NullString `json:"rerank_fusion_method"`
	UseBm25Index       sql.NullBool   `json:"use_bm25_index"`
	UseContextEmbed    sql.NullBool   `json:"use_context_embed"`
	EmbeddingProvider  sql.NullString `json:"embedding_provider"`
	EmbeddingModel     sql.NullString `json:"embedding_model"`
	EmbeddingOptions   sql.NullString `json:"embedding_options"`
	VectorStore        sql.NullString `json:"vector_store"`
	VectorDimension    sql.NullInt64  `json:"vector_dimension"`
	VectorMetricType   sql.NullString `json:"vector_metric_type"`
	ContextEmbedPrompt sql.NullString `json:"context_embed_prompt"`
}

func (q *Queries) CreateCorpus(ctx context.Context, arg CreateCorpusParams) (*Corpu, error) {
	row := q.queryRow(ctx, q.createCorpusStmt, createCorpus,
		arg.Name,
		arg.Description,
		arg.CollectionName,
		arg.RerankFusionMethod,
		arg.UseBm25Index,
		arg.UseContextEmbed,
		arg.EmbeddingProvider,
		arg.EmbeddingModel,
		arg.EmbeddingOptions,
		arg.VectorStore,
		arg.VectorDimension,
		arg.VectorMetricType,
		arg.ContextEmbedPrompt,
	)
	var i Corpu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CollectionName,
		&i.RerankFusionMethod,
		&i.VectorStore,
		&i.UseBm25Index,
		&i.UseContextEmbed,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.EmbeddingProvider,
		&i.EmbeddingModel,
		&i.EmbeddingOptions,
		&i.VectorDimension,
		&i.VectorMetricType,
		&i.ContextEmbedPrompt,
	)
	return &i, err
}

const deleteCorpus = `-- name: DeleteCorpus :exec
DELETE FROM corpus WHERE name = ?
`

func (q *Queries) DeleteCorpus(ctx context.Context, name string) error {
	_, err := q.exec(ctx, q.deleteCorpusStmt, deleteCorpus, name)
	return err
}

const getCorpus = `-- name: GetCorpus :one
SELECT id, name, description, collection_name, rerank_fusion_method, vector_store, use_bm25_index, use_context_embed, created_at, last_updated_at, embedding_provider, embedding_model, embedding_options, vector_dimension, vector_metric_type, context_embed_prompt FROM corpus WHERE name = ?
`

func (q *Queries) GetCorpus(ctx context.Context, name string) (*Corpu, error) {
	row := q.queryRow(ctx, q.getCorpusStmt, getCorpus, name)
	var i Corpu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CollectionName,
		&i.RerankFusionMethod,
		&i.VectorStore,
		&i.UseBm25Index,
		&i.UseContextEmbed,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.EmbeddingProvider,
		&i.EmbeddingModel,
		&i.EmbeddingOptions,
		&i.VectorDimension,
		&i.VectorMetricType,
		&i.ContextEmbedPrompt,
	)
	return &i, err
}

const listCorpus = `-- name: ListCorpus :many
SELECT id, name, description, collection_name, rerank_fusion_method, vector_store, use_bm25_index, use_context_embed, created_at, last_updated_at, embedding_provider, embedding_model, embedding_options, vector_dimension, vector_metric_type, context_embed_prompt FROM corpus
`

func (q *Queries) ListCorpus(ctx context.Context) ([]*Corpu, error) {
	rows, err := q.query(ctx, q.listCorpusStmt, listCorpus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Corpu
	for rows.Next() {
		var i Corpu
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CollectionName,
			&i.RerankFusionMethod,
			&i.VectorStore,
			&i.UseBm25Index,
			&i.UseContextEmbed,
			&i.CreatedAt,
			&i.LastUpdatedAt,
			&i.EmbeddingProvider,
			&i.EmbeddingModel,
			&i.EmbeddingOptions,
			&i.VectorDimension,
			&i.VectorMetricType,
			&i.ContextEmbedPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorpus = `-- name: UpdateCorpus :one
UPDATE corpus
SET description = ?, collection_name = ?, rerank_fusion_method = ?, use_bm25_index = ?, use_context_embed = ?, embedding_provider = ?, embedding_model = ?, embedding_options = ?, vector_store = ?, vector_dimension = ?, vector_metric_type = ?, context_embed_prompt = ?
WHERE name = ?
RETURNING id, name, description, collection_name, rerank_fusion_method, vector_store, use_bm25_index, use_context_embed, created_at, last_updated_at, embedding_provider, embedding_model, embedding_options, vector_dimension, vector_metric_type, context_embed_prompt
`

type UpdateCorpusParams struct {
	Description        sql.NullString `json:"description"`
	CollectionName     sql.NullString `json:"collection_name"`
	RerankFusionMethod sql.NullString `json:"rerank_fusion_method"`
	UseBm25Index       sql.NullBool   `json:"use_bm25_index"`
	UseContextEmbed    sql.NullBool   `json:"use_context_embed"`
	EmbeddingProvider  sql.NullString `json:"embedding_provider"`
	EmbeddingModel     sql.NullString `json:"embedding_model"`
	EmbeddingOptions   sql.NullString `json:"embedding_options"`
	VectorStore        sql.NullString `json:"vector_store"`
	VectorDimension    sql.NullInt64  `json:"vector_dimension"`
	VectorMetricType   sql.NullString `json:"vector_metric_type"`
	ContextEmbedPrompt sql.NullString `json:"context_embed_prompt"`
	Name               string         `json:"name"`
}

func (q *Queries) UpdateCorpus(ctx context.Context, arg UpdateCorpusParams) (*Corpu, error) {
	row := q.queryRow(ctx, q.updateCorpusStmt, updateCorpus,
		arg.Description,
		arg.CollectionName,
		arg.RerankFusionMethod,
		arg.UseBm25Index,
		arg.UseContextEmbed,
		arg.EmbeddingProvider,
		arg.EmbeddingModel,
		arg.EmbeddingOptions,
		arg.VectorStore,
		arg.VectorDimension,
		arg.VectorMetricType,
		arg.ContextEmbedPrompt,
		arg.Name,
	)
	var i Corpu
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CollectionName,
		&i.RerankFusionMethod,
		&i.VectorStore,
		&i.UseBm25Index,
		&i.UseContextEmbed,
		&i.CreatedAt,
		&i.LastUpdatedAt,
		&i.EmbeddingProvider,
		&i.EmbeddingModel,
		&i.EmbeddingOptions,
		&i.VectorDimension,
		&i.VectorMetricType,
		&i.ContextEmbedPrompt,
	)
	return &i, err
}
