// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
)

type Job struct {
	ID            int64           `json:"id"`
	StreamID      int64           `json:"stream_id"`
	Sorted        int64           `json:"sorted"`
	Name          string          `json:"name"`
	Type          string          `json:"type"`
	Description   sql.NullString  `json:"description"`
	LlmModel      sql.NullString  `json:"llm_model"`
	Temperature   sql.NullFloat64 `json:"temperature"`
	TopP          sql.NullFloat64 `json:"top_p"`
	MaxTokens     sql.NullInt64   `json:"max_tokens"`
	Template      sql.NullString  `json:"template"`
	SystemPrompt  sql.NullString  `json:"system_prompt"`
	Method        sql.NullString  `json:"method"`
	Endpoint      sql.NullString  `json:"endpoint"`
	Params        sql.NullString  `json:"params"`
	Output        sql.NullString  `json:"output"`
	OutputParses  sql.NullString  `json:"output_parses"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	SearchEngine  sql.NullString  `json:"search_engine"`
	SearchOptions sql.NullString  `json:"search_options"`
	QueryField    sql.NullString  `json:"query_field"`
	OutputField   sql.NullString  `json:"output_field"`
}

type Stream struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Level       sql.NullInt64  `json:"level"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
