// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
)

type Corpu struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Description        sql.NullString `json:"description"`
	CollectionName     sql.NullString `json:"collection_name"`
	RerankFusionMethod sql.NullString `json:"rerank_fusion_method"`
	VectorStore        sql.NullString `json:"vector_store"`
	UseBm25Index       sql.NullBool   `json:"use_bm25_index"`
	UseContextEmbed    sql.NullBool   `json:"use_context_embed"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	LastUpdatedAt      sql.NullTime   `json:"last_updated_at"`
	EmbeddingProvider  sql.NullString `json:"embedding_provider"`
	EmbeddingModel     sql.NullString `json:"embedding_model"`
	EmbeddingOptions   sql.NullString `json:"embedding_options"`
	VectorDimension    sql.NullInt64  `json:"vector_dimension"`
	VectorMetricType   sql.NullString `json:"vector_metric_type"`
	ContextEmbedPrompt sql.NullString `json:"context_embed_prompt"`
}

type Job struct {
	ID            int64           `json:"id"`
	StreamID      int64           `json:"stream_id"`
	Sorted        int64           `json:"sorted"`
	Name          string          `json:"name"`
	Type          string          `json:"type"`
	Description   sql.NullString  `json:"description"`
	LlmModel      sql.NullString  `json:"llm_model"`
	Temperature   sql.NullFloat64 `json:"temperature"`
	TopP          sql.NullFloat64 `json:"top_p"`
	MaxTokens     sql.NullInt64   `json:"max_tokens"`
	Template      sql.NullString  `json:"template"`
	SystemPrompt  sql.NullString  `json:"system_prompt"`
	Method        sql.NullString  `json:"method"`
	Endpoint      sql.NullString  `json:"endpoint"`
	Params        sql.NullString  `json:"params"`
	Output        sql.NullString  `json:"output"`
	OutputParses  sql.NullString  `json:"output_parses"`
	CreatedAt     sql.NullTime    `json:"created_at"`
	SearchEngine  sql.NullString  `json:"search_engine"`
	SearchOptions sql.NullString  `json:"search_options"`
	QueryField    sql.NullString  `json:"query_field"`
	OutputField   sql.NullString  `json:"output_field"`
	LlmProvider   sql.NullString  `json:"llm_provider"`
}

type Stream struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Level       sql.NullInt64  `json:"level"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}
